DROP  PROCEDURE DESCASA.AGENCIAS_SP_CABECERA_DUAA
 CREATE PROCEDURE DESCASA.AGENCIAS_SP_CABECERA_DUAA ( 
	IN IN_OS VARCHAR(15)) 
	
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DESCASA.AGENCIAS_SP_CABECERA_DUAA 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
		 
	 --Declaracion de Variables 
	 
	DECLARE DORDENES VARCHAR ( 25 ) DEFAULT '' ;
	DECLARE DRNSLIB VARCHAR ( 25 ) DEFAULT '' ; 				
	DECLARE NUMERACION VARCHAR ( 50 ) DEFAULT '' ; 
	DECLARE CADENA VARCHAR ( 50 ) DEFAULT '' ;			 
	DECLARE STRSQL VARCHAR ( 5000 ) DEFAULT '' ;	 
	DECLARE P1 CURSOR WITH RETURN FOR S1 ; 
		 
	SET DRNSLIB = 'DC@RNSLIB' ; 
	
				 
	SET STRSQL = 'SELECT A.TPSRVA,RTRIM(B.TCMTSR)AS TCMTSR,A.NORDSR,RTRIM(A.REFRNC)AS REFRNC,A.VALMRC,A.VALFLT,
		A.VALSEG, A.IMPCIF, A.VALADV, A.VALSBT, A.VALIGV,
		A.VALIPM, A.FFACTU, A.FACTUR
		FROM ' || DRNSLIB || '.DUAA A
		LEFT OUTER JOIN ' || DRNSLIB || '.RZZK65 B ON A.TPSRVA=B.TPSRVA AND A.CCMPN=B.CCMPN
		WHERE A.NORDSR = ''' || IN_OS || ''' ' ; 
		 							 
	 
PREPARE S1 FROM STRSQL ;	 
OPEN P1 ;	 
			 	 
END  
	
GO

GRANT ALL PRIVILEGES ON PROCEDURE DESCASA.AGENCIAS_SP_CABECERA_DUAA TO PUBLIC

 