 CREATE PROCEDURE LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_CONTROLGASTOS ( 
	IN XPNCDTR VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_CONTROLGASTOS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CS , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = LIBORDAG , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	 
	DECLARE WK_FULTAC NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	DECLARE WK_HULTAC NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	 
	DECLARE WK_CPLNC1 NUMERIC ( 1 , 0 ) ; 
	DECLARE WK_TPCOOB VARCHAR ( 1 ) DEFAULT ' ' ; 
	DECLARE WK_NUMLIN NUMERIC ( 1 , 0 ) DEFAULT 0 ; 
	DECLARE WK_CULUSA VARCHAR ( 15 ) DEFAULT ' ' ; 
	DECLARE WK_PNNMOS VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDRG VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDZO VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNDCPL VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDOP VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCASCI VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCTPOS VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DDREGI VARCHAR ( 30 ) DEFAULT ' ' ; 
	DECLARE WK_DCREFE VARCHAR ( 30 ) DEFAULT ' ' ; 
	DECLARE WK_FNCDPR VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCDSME VARCHAR ( 60 ) DEFAULT ' ' ; 
	DECLARE WK_DNTPCA VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCGSIL VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DNPDEC NUMERIC ( 10 , 0 ) DEFAULT 0 ;		 
	DECLARE WK_DCINTE VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_FECHA1 NUMERIC ( 10 , 0 ) ; 
	 
	SET	WK_FULTAC = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HULTAC = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
  
SET WK_CPLNC1 = 1 ; 
SET WK_TPCOOB = 'C' ; 
SET WK_NUMLIN = 1 ; 
SET WK_CULUSA = 'VISUAL BAS' ; 
  
SELECT PNNMOS , PNCDRG , PNCDZO , PNDCPL , PNCDOP , DCASCI , DCTPOS , DDREGI , DCREFE , 
	FNCDPR , DCDSME , DNTPCA , DCGSIL , DNPDEC 
	INTO WK_PNNMOS , WK_PNCDRG , WK_PNCDZO , WK_PNDCPL , WK_PNCDOP , WK_DCASCI , WK_DCTPOS , WK_DDREGI , WK_DCREFE , 
	WK_FNCDPR , WK_DCDSME , WK_DNTPCA , WK_DCGSIL , WK_DNPDEC 
FROM LIBORDAG . DORDENES WHERE PNCDTR = XPNCDTR ; 
  
IF NOT EXISTS ( SELECT NORDSR FROM DC@RNSLIB . RZIM51 WHERE CCMPN = 'FZ' 
AND CDVSN = 'A' AND CZNFCC = WK_PNCDZO AND CPLNDV = WK_PNDCPL AND TPSRVA = WK_DCTPOS AND NORDSR = WK_PNNMOS ) THEN 
  
INSERT INTO DC@RNSLIB . RZIM51 
( CCMPN , CDVSN , CZNFCC , CPLNDV , TPSRVA , 
NORDSR , SESTRG , FULTAC , HULTAC , CULUSA ) 
VALUES ( 'FZ' , 'A' , WK_PNCDZO , WK_PNDCPL , WK_DCTPOS , 
WK_PNNMOS , 'A' , WK_FULTAC , WK_HULTAC , WK_CULUSA ) ; 
  
	END IF ; 
  
  
  
END  ;
