 DROP  PROCEDURE DESCASA.SP_AGENCIAS_ORDENCOMPRA
  
  CREATE PROCEDURE DESCASA.SP_AGENCIAS_ORDENCOMPRA ( 
	IN IN_TIPOORDEN NUMERIC(5) , 	
	IN IN_NROORDENC VARCHAR(30)
	) 
	
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DESCASA.SP_AGENCIAS_ORDENCOMPRA 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
		 
	 --Declaracion de Variables 
	 
	DECLARE STRSQL VARCHAR ( 5000 ) DEFAULT '' ;	 
	DECLARE P1 CURSOR WITH RETURN FOR S1 ; 
		 
	
/*				 
	SET STRSQL = ' SELECT A.NMRODC, A.CSRVNV,B.NOMVAR,A.VALMRC,A.STPGCT
				   FROM LIBORDAG.DDTCOC A
                   INNER JOIN DC@RNSLIB.RZOL31Z B ON A.CSRVNV = B.NRVARB
                   WHERE NMRODC = ''' || IN_NROORDENC || ''' AND STPGCT = ' || IN_TIPOORDEN || '' ;  */
	
	SET STRSQL =  'SELECT A.NMRODC, A.CSRVNV,B.NOMVAR,SUM (A.VALMRC) AS VALMRC,A.STPGCT
                  FROM LIBORDAG.DDTCOC A
                  INNER JOIN DC@RNSLIB.RZOL31Z B ON A.CSRVNV = B.NRVARB
                  WHERE NMRODC = ''' || IN_NROORDENC || ''' AND STPGCT = ' || IN_TIPOORDEN || ' GROUP BY NMRODC,CSRVNV,NOMVAR,STPGCT ';	 
		 
		 		 
	 
	PREPARE S1 FROM STRSQL ;	 
	OPEN P1 ;	 

 
	 
END  
	
GO

GRANT ALL PRIVILEGES ON PROCEDURE DESCASA.SP_AGENCIAS_ORDENCOMPRA TO PUBLIC

