 DROP  PROCEDURE DESCASA.SP_CONSULTA_SEG_WEB
 CREATE PROCEDURE DESCASA.SP_CONSULTA_SEG_WEB ( 
	IN IN_OS VARCHAR(15) , 
	IN IN_REFER VARCHAR(30) , 
	IN IN_NAVE VARCHAR(25) , 
	IN IN_CANAL VARCHAR(15) , 
	IN IN_BL VARCHAR(25) , 
	IN IN_AFORO VARCHAR(10) , 
	IN IN_RETIRO VARCHAR(10) , 
	IN IN_NUMERACION VARCHAR(10),
	IN IN_CLIENTE VARCHAR(20)) 
	
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DESCASA.SP_CONSULTA_SEG_WEB 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
		 
	 --Declaracion de Variables 
	 
	DECLARE DORDENES VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE CREGIMEN VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE COPERACI VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE DCLIENTE VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE DSEGIMP VARCHAR ( 25 ) DEFAULT '' ;	 
	DECLARE DSEGEXP VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE CODIGOS VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE DVOLANTE VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE RACBASOS VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE DDOCEMB VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE DAGCARGA VARCHAR ( 25 ) DEFAULT '' ; 
	DECLARE AFORO VARCHAR ( 50 ) DEFAULT '' ; 
	DECLARE RETIRO VARCHAR ( 50 ) DEFAULT '' ; 
	DECLARE NUMERACION VARCHAR ( 50 ) DEFAULT '' ; 
	DECLARE CADENA VARCHAR ( 50 ) DEFAULT '' ;			 
	DECLARE STRSQL VARCHAR ( 5000 ) DEFAULT '' ;	 
	DECLARE P1 CURSOR WITH RETURN FOR S1 ; 
		 
	SET DORDENES = 'LIBORDAG.DORDENES' ; 
	SET CREGIMEN = 'LIBORDAG.CREGIMEN' ; 
	SET COPERACI = 'LIBORDAG.COPERACI' ; 
	SET DCLIENTE = 'LIBORDAG.DCLIENTE' ; 
	SET DSEGIMP = 'LIBORDAG.DSEGIMP' ; 
	SET DSEGEXP = 'LIBORDAG.DSEGEXP' ; 
	SET CODIGOS = 'LIBORDAG.CODIGOS' ; 
	SET DVOLANTE = 'LIBORDAG.DVOLANTE' ; 
	SET RACBASOS = 'LIBORDAG.RACBASOS' ; 
	SET DDOCEMB = 'LIBORDAG.DDOCEMB' ; 
	SET DAGCARGA = 'LIBORDAG.DAGCARGA' ; 
	SET CADENA = 'ORDER BY A.DDREGI DESC' ; 
				 
	SET STRSQL = 'SELECT A.PNNMOS AS ORDEN, A.DCTPOS AS TIPO,
				  CASE WHEN A.FNCDPR = ''00''
				  THEN ''Normal''  WHEN A.FNCDPR = ''01'' 
				  THEN ''Urgente'' WHEN A.FNCDPR = ''02''
				  THEN ''Socorro'' WHEN A.FNCDPR = ''10''
				  THEN ''Anticipado'' END AS SITUACION,
				  SUBSTR(CAST(A.DDREGI AS VARCHAR(50)),9,2) || ''/'' ||
				  SUBSTR(CAST(A.DDREGI AS VARCHAR(50)),6,2) || ''/'' ||
				  SUBSTR(CAST(A.DDREGI AS VARCHAR(50)),1,4) AS DDREGI,
				  B.DCDSRG AS REGIMEN, C.DCDSOP AS OPERACION, G.DCDSCD AS CARGA,
				  H.DCDSCD AS CANAL, D.DCNMCL AS CLIENTE, A.DCREFE AS REFERENCIA,
				  A.DCDSME AS MERCADERIA,  P.DCNAVE AS NAVE,
				  SUBSTR(CAST(P.DDNAVE AS VARCHAR(50)),9,2) || ''/'' ||
				  SUBSTR(CAST(P.DDNAVE AS VARCHAR(50)),6,2) || ''/'' ||
				  SUBSTR(CAST(P.DDNAVE AS VARCHAR(50)),1,4)  AS ESTIMADO,
				  SUBSTR(CAST(I.DDNAVE AS VARCHAR(50)),9,2) || ''/'' ||
				  SUBSTR(CAST(I.DDNAVE AS VARCHAR(50)),6,2) || ''/'' ||
                  SUBSTR(CAST(I.DDNAVE AS VARCHAR(50)),1,4) AS LLEGADA, 
                  SUBSTR(CAST(I.DDTDES AS VARCHAR(50)),9,2) || ''/'' ||
				  SUBSTR(CAST(I.DDTDES AS VARCHAR(50)),6,2) || ''/'' ||
                  SUBSTR(CAST(I.DDTDES AS VARCHAR(50)),1,4) AS TERMINO,  
                  J.DCDSAB AS TERMINAL, P.PCNMDC AS BL, I.DCNMMA AS MANIFIESTO,
				  I.DCNMDM AS NUMERO,  Q.DCDSCD AS AGMARITIMO, S.DCDSCD AS AGCARGA, A.DCDUIDUE AS DUA,
				CASE WHEN SUBSTR(A.DCTPOS, 1, 1) = ''I''
				THEN 
				SUBSTR(CAST(E.DDNUME AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(E.DDNUME AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(E.DDNUME AS VARCHAR(50)),1,4)
				WHEN SUBSTR(A.DCTPOS, 1, 1) = ''E'' THEN
				SUBSTR(CAST(F.DDNDUE AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(F.DDNDUE AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(F.DDNDUE AS VARCHAR(50)),1,4) END AS NUMERACION, 
				SUBSTR(CAST(E.DDPGDR AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(E.DDPGDR AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(E.DDPGDR AS VARCHAR(50)),1,4) AS PAGO, 
				E.DMTTDR AS MONTO,  K.DDINIA AS SENASA,
				SUBSTR(CAST(L.DDFINA AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(L.DDFINA AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(L.DDFINA AS VARCHAR(50)),1,4) AS AFORO, CAST(M.DDINIA AS DATE) AS PRESENTACION,
				SUBSTR(CAST(N.DDINIA AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(N.DDINIA AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(N.DDINIA AS VARCHAR(50)),1,4) AS LEVANTE, 
				SUBSTR(CAST(O.DDFINA AS VARCHAR(50)),9,2) || ''/'' ||
				SUBSTR(CAST(O.DDFINA AS VARCHAR(50)),6,2) || ''/'' ||
				SUBSTR(CAST(O.DDFINA AS VARCHAR(50)),1,4) AS RETIRO , T.DCOBSE
				FROM LIBORDAG.DORDENES A
				JOIN LIBORDAG.CREGIMEN B ON A.PNCDRG = B.PNCDRG
				JOIN LIBORDAG.COPERACI C ON A.PNCDOP = C.PNCDOP
				JOIN LIBORDAG.DCLIENTE D ON A.DCASCI = D.DCASCI
				LEFT OUTER JOIN LIBORDAG.DSEGIMP E ON A.PNCDTR = E.PNCDTR
				LEFT OUTER JOIN LIBORDAG.DSEGEXP F ON A.PNCDTR = F.PNCDTR
				LEFT OUTER JOIN LIBORDAG.PCODIGOS G ON A.DNTPCA = G.PNCDIN AND G.PCTABL = ''TIPCARGA''
				LEFT OUTER JOIN LIBORDAG.PCODIGOS H ON A.DCCANA = H.PNCDIN AND H.PCTABL = ''CANAL''
				LEFT OUTER JOIN LIBORDAG.DVOLANTE I ON A.PNCDTR = I.PNCDTR
				LEFT OUTER JOIN LIBORDAG.PCODIGOS J ON I.FNCDDP = J.PNCDIN AND J.PCTABL = ''DEPOSITO''
				LEFT OUTER JOIN LIBORDAG.RACBASOS K ON A.PNCDTR = K.PNCDTR AND K.PNCDAC = ''I14''
				LEFT OUTER JOIN LIBORDAG.RACBASOS L ON A.PNCDTR = L.PNCDTR AND L.PNCDAC = ''I13''
				LEFT OUTER JOIN LIBORDAG.RACBASOS M ON A.PNCDTR = M.PNCDTR AND M.PNCDAC = ''I16''
				LEFT OUTER JOIN LIBORDAG.RACBASOS N ON A.PNCDTR = N.PNCDTR AND N.PNCDAC = ''I12''
				LEFT OUTER JOIN LIBORDAG.RACBASOS O ON A.PNCDTR = O.PNCDTR AND O.PNCDAC = ''I15''
				LEFT OUTER JOIN LIBORDAG.RACBASOS T ON A.PNCDTR = T.PNCDTR AND T.PNCDAC = ''I23''
				LEFT OUTER JOIN LIBORDAG.DDOCEMB P ON A.PNCDTR = P.PNCDTR
				LEFT OUTER JOIN LIBORDAG.PCODIGOS Q ON E.DCAGMR = Q.PNCDIN AND Q.PCTABL = ''AGETRAN''
				LEFT OUTER JOIN LIBORDAG.DAGCARGA R ON A.PNCDTR = R.PNCDTR
				LEFT OUTER JOIN LIBORDAG.PCODIGOS S ON R.PNCDIN = S.PNCDIN AND S.PCTABL = ''AGECARGA''
				WHERE A.PNCDCO = ''FZ'' AND A.PNCDNG = ''A'' AND A.PNDCPL = ''1'' AND A.PNCDZO = ''1''
				AND A.DCESTA = ''A'' AND A.DCASCI = ''' || IN_CLIENTE || '''  AND CHAR(PNNMOS) LIKE ''%' || IN_OS || '%'' AND A.DCREFE LIKE ''%' || IN_REFER || '%''
				AND A.DCDSME LIKE ''%' || IN_NAVE || '%'' AND G.DCDSCD LIKE ''%' || IN_CANAL || '%'' AND P.PCNMDC LIKE ''%' || IN_BL || '%'' ' ; 
		 
			 --	''%'|| IN_TRDCCL ||'%'' 
				 
	IF ( IN_AFORO <> ' ' ) THEN 
			SET AFORO = 'AND CAST(L.DDFINA AS DATE)= ''' || IN_AFORO || '''' ;	 
			SET STRSQL = STRSQL || AFORO ; 
		END IF ; 
	 
		IF ( IN_RETIRO <> ' ' ) THEN 
			SET RETIRO = 'AND CAST(O.DDFINA AS DATE)= ''' || IN_RETIRO || '''' ; 
			SET STRSQL = STRSQL || RETIRO ; 
	END IF ; 
	 
	IF ( IN_NUMERACION <> ' ' ) THEN 
			SET NUMERACION = 'AND CAST(E.DDNUME AS DATE)= ''' || IN_NUMERACION || '''' ; 
			SET STRSQL = STRSQL || NUMERACION ; 
	END IF ; 
	 
			SET STRSQL = STRSQL || CADENA ; 
	 
	 
		PREPARE S1 FROM STRSQL ;	 
	OPEN P1 ;	 
--	SET VAL_SAL = STRSQL;	 
		 
	 --' || StrBusqueda ||' 
		 
	 
END  
	
GO

GRANT ALL PRIVILEGES ON PROCEDURE DESCASA.SP_CONSULTA_SEG_WEB TO PUBLIC

