DROP PROCEDURE LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_ZZ201001

CREATE PROCEDURE LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_ZZ201001 ( 
	IN XPNCDTR VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_ZZ201001 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CS , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = LIBORDAG , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	 
	 
	DECLARE WK_FULTAC NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	DECLARE WK_HULTAC NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	 
	DECLARE WK_CPLNC1 NUMERIC ( 1 , 0 ) ; 
	DECLARE WK_TPCOOB VARCHAR ( 1 ) DEFAULT ' ' ; 
	DECLARE WK_NUMLIN NUMERIC ( 1 , 0 ) DEFAULT 0 ; 
	DECLARE WK_CULUSA VARCHAR ( 15 ) DEFAULT ' ' ; 
	DECLARE WK_PNNMOS VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDRG VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDZO VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNDCPL VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_PNCDOP VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCASCI VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCTPOS VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DDREGI VARCHAR ( 30 ) DEFAULT ' ' ; 
	DECLARE WK_DCREFE VARCHAR ( 30 ) DEFAULT ' ' ; 
	DECLARE WK_FNCDPR VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCDSME VARCHAR ( 60 ) DEFAULT ' ' ; 
	DECLARE WK_DNTPCA VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DCGSIL VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_DNPDEC NUMERIC ( 10 , 0 ) DEFAULT 0 ;		 
	DECLARE WK_DCINTE VARCHAR ( 10 ) DEFAULT ' ' ; 
	DECLARE WK_FECHA1 NUMERIC ( 10 , 0 ) ; 
	 
	 
	SET	WK_FULTAC = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HULTAC = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
  
SET WK_CPLNC1 = 1 ; 
SET WK_TPCOOB = 'C' ; 
SET WK_NUMLIN = 1 ; 
SET WK_CULUSA = 'VISUAL BAS' ; 
	 
	SELECT PNNMOS , PNCDRG , PNCDZO , PNDCPL , PNCDOP , DCASCI , DCTPOS , DDREGI , DCREFE , 
	FNCDPR , DCDSME , DNTPCA , DCGSIL , DNPDEC 
	INTO WK_PNNMOS , WK_PNCDRG , WK_PNCDZO , WK_PNDCPL , WK_PNCDOP , WK_DCASCI , WK_DCTPOS , WK_DDREGI , WK_DCREFE , 
	WK_FNCDPR , WK_DCDSME , WK_DNTPCA , WK_DCGSIL , WK_DNPDEC 
FROM LIBORDAG . DORDENES WHERE PNCDTR = XPNCDTR ; 
  
IF WK_DCGSIL IS NULL THEN 
		SET WK_DCGSIL = '0' ; 
	ELSE 
		SET WK_DCGSIL = SUBSTRING ( WK_DCGSIL , 0 , 9 ) ; 
	END IF ;		 
  
IF WK_DCGSIL <> '0' THEN 
		SET WK_DCINTE = '*' ; 
ELSE 
SET WK_DCINTE = '' ; 
SET WK_DCGSIL = '0' ; 
END IF ; 
  
  
IF WK_DCREFE IS NULL THEN 
		SET WK_DCREFE = ' ' ; 
END IF ; 
IF WK_DNPDEC IS NULL THEN 
		SET WK_DNPDEC = '0' ; 
END IF ; 
  
SET WK_DDREGI = SUBSTRING ( WK_DDREGI , 1 , 4 ) CONCAT SUBSTRING ( WK_DDREGI , 6 , 2 ) CONCAT SUBSTRING ( WK_DDREGI , 9 , 2 ) ; 
SET WK_FECHA1 = CAST ( WK_DDREGI AS NUMERIC ( 8 ) )	; 
  
--IF WK_PNCDOP THEN 
  
  
IF EXISTS ( SELECT NORDSR FROM DC@RNSLIB . ZZ201001 WHERE CCMPN = 'FZ' 
AND CDVSN = 'A' 
AND CZNFCC = WK_PNCDZO 
AND CPLNDV = WK_PNDCPL 
AND TPSRVA = WK_DCTPOS 
AND NORDSR = WK_PNNMOS ) THEN 
  
		UPDATE DC@RNSLIB . ZZ201001 
		SET 
		NORDST = 0 , 
		DESURG = SUBSTRING ( WK_FNCDPR , 1 , 1 ) , 
		TIPDES = SUBSTRING ( WK_FNCDPR , 2 , 1 ) , 
		FORDSR = WK_FECHA1 , 
		CCLNT = WK_DCASCI , 
		CPLNCL = WK_CPLNC1 , 
		TPOPEA = WK_PNCDRG , 
		TPOPRG = SUBSTRING ( WK_PNCDOP , 2 , 2 ) , 
		PRTDCL = WK_DNPDEC , 
		CTPCVH = WK_DNTPCA , 
		DSREFC = WK_DCREFE , 
		DSMARC = WK_DCREFE , 
		DSMERC = WK_DCDSME , 
		SSRVIN = WK_DCINTE , 
		ESTREG = 'A' , 
		DATCHG = WK_FULTAC , 
		TIMCHG = WK_HULTAC , 
		USRCHG = WK_CULUSA 
		WHERE CCMPN = 'FZ' 
		AND CDVSN = 'A' 
		AND CZNFCC = WK_PNCDZO 
		AND CPLNDV = WK_PNDCPL 
		AND TPSRVA = WK_DCTPOS 
		AND NORDSR = WK_PNNMOS ; 
  
ELSE 
  
  
IF WK_DCDSME <> '' THEN 
SET WK_DCDSME = SUBSTRING ( WK_DCDSME , 1 , 30 ) ; 
END IF ; 
  
  
		INSERT INTO DC@RNSLIB . ZZ201001 ( CCMPN , CDVSN , CZNFCC , CPLNDV , TPSRVA , NORDSR , 
		NORDST , DESURG , TIPDES , FORDSR , CCLNT , CPLNCL ,		 
		TPOPEA , TPOPRG , PRTDCL , CTPCVH , DSREFC , DSMERC , 
		DSMARC , SSRVIN , ESTREG , DATCRT , USRCRT ) 
		VALUES ( 'FZ' , 'A' , WK_PNCDZO , WK_CPLNC1 , WK_DCTPOS , WK_PNNMOS , 
		0 , SUBSTRING ( WK_FNCDPR , 1 , 1 ) , SUBSTRING ( WK_FNCDPR , 2 , 1 ) , WK_FECHA1 , WK_DCASCI , WK_CPLNC1 ,		 
		WK_PNCDRG , WK_PNCDOP , WK_DNPDEC , WK_DNTPCA , WK_DCREFE , WK_DCREFE , 
		WK_DCDSME , WK_DCINTE , 'A' , WK_FULTAC , WK_CULUSA ) ; 
  
END IF ; 
  
  
END  

GO

GRANT ALL PRIVILEGES ON PROCEDURE LIBORDAG.SP_WEBAGENCIAS_CREAR_OS_ZZ201001 TO PUBLIC
 