CREATE PROCEDURE DC@RNSLIB.SP_SOLSEGORD_IMP_DISTRIBUCION_ORDEN_COMPRA ( 
	IN IN_NORDSR VARCHAR(10) , 
	IN IN_TIPO VARCHAR(10) , 
	IN IN_ZONA VARCHAR(2) , 
	IN IN_CCLNT NUMERIC(10, 0) , 
	IN IN_RUBRO VARCHAR(2) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_SOLSEGORD_IMP_DISTRIBUCION_ORDEN_COMPRA 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = DC@RNSLIB , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN ATOMIC 
	 
	 
	DECLARE WK_FECHA NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	DECLARE WK_HORA NUMERIC ( 8 , 0 ) DEFAULT 0 ; 
	DECLARE WK_VALOR NUMERIC ( 18 , 5 ) DEFAULT 0 ; 
	DECLARE WK_VALOR1 NUMERIC ( 18 , 5 ) DEFAULT 0 ; 
	 
	 -- Obtengo la fecha y hora actual 
	SET	WK_FECHA = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
	SET	WK_HORA = HOUR ( CURRENT TIME ) * 10000 + MINUTE ( CURRENT TIME ) * 100 + SECOND ( CURRENT TIME ) ; 
	 
	 
	FOR FILA AS C1 CURSOR FOR 
	 
		SELECT NRVARB FROM DC@RNSLIB . ZZ202201 
		WHERE NRVARB IN ( 41 , 42 , 43 , 44 , 46 , 47 , 57 ) 
		ORDER BY NRVARB 
			 
	DO 
	 
		FOR FILA1 AS C2 CURSOR FOR 
		 
		SELECT * FROM DC@RNSLIB . DUAA1 WHERE NORDSR = IN_NORDSR 
		 
		DO 
			 
		IF FILA . NRVARB = 41 THEN  -- ADVALOREM 
		 
			SELECT SUM ( VALADV ) 
			INTO WK_VALOR 
			FROM DC@RNSLIB . DUAA1 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC ; 
			 
		ELSEIF FILA . NRVARB = 42 THEN  --IGV 
		 
			SELECT SUM ( VALIGV ) 
			INTO WK_VALOR 
			FROM DC@RNSLIB . DUAA1 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC ; 
					 
		ELSEIF FILA . NRVARB = 43 THEN  --IPM 
		 
			SELECT SUM ( VALIPM ) 
			INTO WK_VALOR 
			FROM DC@RNSLIB . DUAA1 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC ; 
					 
		ELSEIF FILA . NRVARB = 44 THEN  --TASA DESPACHO 
					 
			SELECT SUM ( VALRNP ) 
			INTO WK_VALOR 
			FROM DC@RNSLIB . DUAA1 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC ; 
			 
		ELSEIF FILA . NRVARB = 46 THEN  --46 COMISION AGENCIAMIENTO 
		 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 2 ; 
			 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR1 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 3 ; 
				 
		ELSEIF FILA . NRVARB = 47 THEN	 --47 GASTOS OPEARTIVOS AG.(AVISO DE DEBITO) 
					 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 2 ; 
			 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR1 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 3 ; 
	 
			 
		ELSEIF FILA . NRVARB = 57 THEN	 --57 TRACCION 
		 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 2 ; 
			 
			SELECT SUM ( VALMRC ) 
			INTO WK_VALOR1 
			FROM LIBORDAG . DCOSTOS 
			WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND CSRVNV = FILA . NRVARB AND STPGCT = 3 ; 
		 
		END IF ; 
					 
		IF EXISTS ( SELECT * FROM LIBORDAG . DDTCOC WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND STPGCT = 2 AND CSRVNV = FILA . NRVARB ) THEN 
	 
			UPDATE LIBORDAG . DDTCOC SET 
			VALMRC = WK_VALOR , 
			FULTAC = WK_FECHA , 
			HULTAC = WK_HORA 
			WHERE NMRODC = FILA1 . NMRODC AND 
			NMITOC = FILA1 . NMITOC AND 
			CSRVNV = FILA . NRVARB AND 
			STPGCT = 2 ; 
		ELSE 
			IF WK_VALOR IS NOT NULL THEN 
				INSERT INTO LIBORDAG . DDTCOC ( NMRODC , NMITOC , CSRVNV , VALMRC , STPGCT , SESTRG , FULTAC , HULTAC , CULUSA ) 
				VALUES ( FILA1 . NMRODC , FILA1 . NMITOC , FILA . NRVARB , WK_VALOR , 2 , 'A' , WK_FECHA , WK_HORA , 'MIGRACION' ) ;	 
			END IF ; 
			 
		END IF ;	 
		 
		IF FILA . NRVARB = 46 OR FILA . NRVARB = 47 OR FILA . NRVARB = 57 THEN 
		 
			IF EXISTS ( SELECT * FROM LIBORDAG . DDTCOC WHERE NMRODC = FILA1 . NMRODC AND NMITOC = FILA1 . NMITOC AND STPGCT = 3 AND CSRVNV = FILA . NRVARB ) THEN 
				UPDATE LIBORDAG . DDTCOC SET 
				VALMRC = WK_VALOR1 , 
				FULTAC = WK_FECHA , 
				HULTAC = WK_HORA 
				WHERE NMRODC = FILA1 . NMRODC AND 
				NMITOC = FILA1 . NMITOC AND 
				CSRVNV = FILA . NRVARB AND 
				STPGCT = 3 ; 
			ELSE 
				IF WK_VALOR1 IS NOT NULL THEN 
					INSERT INTO LIBORDAG . DDTCOC ( NMRODC , NMITOC , CSRVNV , VALMRC , STPGCT , SESTRG , FULTAC , HULTAC , CULUSA ) 
					VALUES ( FILA1 . NMRODC , FILA1 . NMITOC , FILA . NRVARB , WK_VALOR1 , 3 , 'A' , WK_FECHA , WK_HORA , 'MIGRACION' ) ;					 
				END IF ; 
			END IF ; 
		 
		END IF ; 
					 
		END FOR ; 
	 
	END FOR ; 
	 
		 
	END  ;
 