CREATE PROCEDURE DC@RNSLIB.SP_SOLSEGORD_IMP_CONSULTA_SEGIMPORTACION_XTRATA1 ( 
	IN IN_ZONA VARCHAR(2) , 
	IN IN_ORDEN VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_SOLSEGORD_IMP_CONSULTA_SEGIMPORTACION_XTRATA1 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
--Declaracion de Variables 
  
DECLARE WK_LIBRERIA VARCHAR ( 10 ) ; 
DECLARE STRSQL VARCHAR ( 6000 ) ; 
DECLARE WK_FECHA_ACT NUMERIC ( 8 ) ; 
DECLARE WK_FECHA DATE ; 
DECLARE WK_FECHA1 VARCHAR ( 20 ) ; 
DECLARE WK_FECHA_SIG DATE ; 
DECLARE WK_FECHA_SIG1 VARCHAR ( 20 ) ; 
DECLARE WK_ANIO VARCHAR ( 4 ) ; 
DECLARE WK_MES VARCHAR ( 2 ) ; 
DECLARE WK_DIA VARCHAR ( 2 ) ; 
DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
SET WK_FECHA_ACT = YEAR ( CURRENT DATE ) * 10000 + MONTH ( CURRENT DATE ) * 100 + DAY ( CURRENT DATE ) ; 
  
SET STRSQL = ' SELECT DISTINCT  PNCDCO,PNCDNG,PNCDZO,PNDCPL,PNNMOS,A.PNCDRG,A.PNCDOP,
 A.DCASCI,DCTPOS,A.DDREGI,DCDSME,B.TCMPCL,DCREFE,
 O.DCDSRG,P.DCDSOP,A.PNCDTR,L.DCDSAB AS DESPAC, K.DCDSRG, A.DCNAVE, A.DDNAVE, 
 A.DDTDES, D.DCDSAB, A.DCCANA, E.DCBLTO,
 E.DDNUME, E.DDPGDR, J.DDINIA AS DDSENA,J.DDFINA AS DOSENA,E.DDINSP, F.DDFINA AS DDAFOR,
 G.DDINIA AS DDPRES, H.DDINIA AS DDLEVA, I.DDFINA AS DDRETI,E.DCNMRM,E.DDCREC,E.DDTREC,
 CASE WHEN A.FNCDPR = ''00'' THEN ''E''   
	WHEN A.FNCDPR = ''01'' THEN ''U'' 
	WHEN A.FNCDPR = ''02'' THEN ''S'' 
	WHEN A.FNCDPR = ''10'' THEN ''A''  
	END AS DESPACHO,B.NRUC,Q.DCDSCD,E.DDANUM,E.DDETLG,E.DDOBVL,E.DDAFPR,E.DDOBDT,E.DDRETI,
	E.DCINDD, S.DDFINA,T.DCOBSE,R.DDRECE,U.TCMPRO,E.DCCTRL,A.DCDUIDUE,E.DDRDDC,E.DDCRDP,
	E.DDOEMB,E.DNSBRE,E.DNDSLB,R.PCNMDC,V.TZNFCC
 FROM LIBORDAG.DORDENES A
 LEFT OUTER JOIN DC@RNSLIB.RZZM01 B ON A.DCASCI = B.CCLNT
 LEFT OUTER JOIN LIBORDAG.DVOLANTE C ON A.PNCDTR = C.PNCDTR AND C.PNCDDC = ''056''
 LEFT OUTER JOIN LIBORDAG.DSEGIMP  E ON A.PNCDTR = E.PNCDTR
 LEFT OUTER JOIN LIBORDAG.PCODIGOS D ON E.DCTRAL = D.PNCDIN AND D.PCTABL = ''DEPOSITO''
 LEFT OUTER JOIN LIBORDAG.RACBASOS F ON A.PNCDTR = F.PNCDTR AND F.PNCDAC = ''I13''
 LEFT OUTER JOIN LIBORDAG.RACBASOS G ON A.PNCDTR = G.PNCDTR AND G.PNCDAC = ''I16''
 LEFT OUTER JOIN LIBORDAG.RACBASOS H ON A.PNCDTR = H.PNCDTR AND H.PNCDAC = ''I12''
 LEFT OUTER JOIN LIBORDAG.RACBASOS I ON A.PNCDTR = I.PNCDTR AND I.PNCDAC = ''I15''
 LEFT OUTER JOIN LIBORDAG.RACBASOS J ON A.PNCDTR = J.PNCDTR AND J.PNCDAC = ''I14''
 LEFT OUTER JOIN LIBORDAG.CREGIMEN K ON A.PNCDRG = K.PNCDRG AND K.DCTPRE = ''I''
 LEFT OUTER JOIN LIBORDAG.PCODIGOS L ON A.FNCDPR = L.PNCDIN AND L.PCTABL = ''PRIODESP''
 LEFT OUTER JOIN LIBORDAG.RACBASOS M ON A.PNCDTR = M.PNCDTR AND M.PNCDAC = ''I18''
 LEFT OUTER JOIN LIBORDAG.RACBASOS S ON A.PNCDTR = S.PNCDTR AND S.PNCDAC = ''I03''
 LEFT OUTER JOIN LIBORDAG.RACBASOS T ON A.PNCDTR = T.PNCDTR AND T.PNCDAC = ''I23''
 LEFT OUTER JOIN LIBORDAG.DDOCOS  R ON A.PNCDTR=R.PNCDTR AND R.PNCDDC=''004''  AND R.DCESTA = ''A''
 LEFT OUTER JOIN LIBORDAG.CREGIMEN  O ON A.PNCDRG= O.PNCDRG
 LEFT OUTER JOIN LIBORDAG.COPERACI P ON A.PNCDOP= P.PNCDOP
 LEFT OUTER JOIN LIBORDAG.PCODIGOS Q ON Q.PNCDIN= A.FCLIQR AND Q.PCTABL = ''LIQUIDAD''
 LEFT OUTER JOIN DC@RNSLIB.RZIK86 U ON A.PNCDRG = U.CODREG AND A.PNCDOP = U.TPOPRG
 LEFT OUTER JOIN DC@RNSLIB.RZIK14 V ON A.PNCDZO =V.CZNFCC
WHERE  PNCDCO =''FZ'' AND PNCDNG=''A''
AND PNDCPL = ''1''  And DCTPOS in (''IM'', ''IA'')
AND A.DCESTA = ''A'' AND B.CCLNT IN( 3177) AND   
A.PNNMOS LIKE CONCAT(''' || IN_ORDEN || ''',''%'')' ; 
  
  
--AND DDREGI > ''' || WK_FECHA1 || ''' 
  
  
SET STRSQL = STRSQL || ' order by  A.PNNMOS ' ; 
  
PREPARE S1 FROM STRSQL ; 
OPEN CU_01 ; 
END  ;
 