 CREATE PROCEDURE DESCASA.SP_SOLSEGORD_IMP_ZONAS ( 
	IN IN_USUARIO VARCHAR(10) FOR MIXED DATA ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC DESCASA.SP_SOLSEGORD_IMP_ZONAS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = DC@RNSLIB , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	 
	 --Declaracion de Variables 
	DECLARE WK_LIBRERIA VARCHAR ( 10 ) ; 
	DECLARE STRSQL VARCHAR ( 600 ) ; 
	DECLARE WK_CLIENTE VARCHAR ( 50 ) ; 
	DECLARE CU_01 CURSOR WITH RETURN FOR S1 ; 
	/*		  
	SET STRSQL = ' SELECT TZNFCC,CZNFCC   
				   FROM DC@RNSLIB.RZIK14  
				   WHERE CZNFCC IN (1,3,5,8,10,26,27) ' ; */ 
				 
	SET STRSQL = 'SELECT B.TZNFCC,B.CZNFCC
				   FROM DC@RNSLIB.RZZM20 A
				   INNER JOIN DC@RNSLIB.RZIK14 B ON A.CZNFCC = B.CZNFCC
				   WHERE A.CCMPN= ''FZ'' AND A.SESTRG=''A'' AND CUSROP =  ''' || IN_USUARIO || '''' ; 
				 
			 
	PREPARE S1 FROM STRSQL ; 
	OPEN CU_01 ; 
--	FETCH CU_01 INTO OU_NOMBRE;	 
  
END  ;
