DROP  PROCEDURE DC@RNSLIB.SP_SOLSEGORD_IMP_INSERTAR_FECHA_CHECKPOINT

CREATE PROCEDURE DC@RNSLIB.SP_SOLSEGORD_IMP_INSERTAR_FECHA_CHECKPOINT ( 
	IN IN_PNCDTR VARCHAR(20) , 
	IN IN_RECEPCION VARCHAR(20) , 
	IN IN_CARGA VARCHAR(20) , 
	IN IN_EMBARQUE VARCHAR(20) , 
	IN IN_SOBREESTADIA NUMERIC(2, 0) , 
	IN IN_DLIBRES NUMERIC(2, 0) , 
	IN IN_DDETLG VARCHAR(20) , 
	IN IN_DDNAVE VARCHAR(20) , 
	IN IN_DDTDES VARCHAR(20) , 
	IN IN_DDOBVL VARCHAR(20) , 
	IN IN_DDAFPR VARCHAR(20) , 
	IN IN_VDDFINA VARCHAR(20) , 
	IN IN_DDANUM VARCHAR(20) , 
	IN IN_DDNUME VARCHAR(20) , 
	IN IN_DDPGDR VARCHAR(20) , 
	IN IN_DDAFOR VARCHAR(20) , 
	IN IN_DDPRES VARCHAR(20) , 
	IN IN_DDLEVA VARCHAR(20) , 
	IN IN_DDRETI VARCHAR(20) , 
	IN IN_DDTREC VARCHAR(20) ) 
	LANGUAGE SQL 
	SPECIFIC DC@RNSLIB.SP_SOLSEGORD_IMP_INSERTAR_FECHA_CHECKPOINT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
		 
	IF IN_RECEPCION = '' THEN 
		SET IN_RECEPCION = NULL ; 
	END IF ; 
	 
	IF IN_CARGA = '' THEN 
		SET IN_CARGA = NULL ; 
	END IF ; 
	 
	IF IN_EMBARQUE = '' THEN 
		SET IN_EMBARQUE = NULL ; 
	END IF ; 
	 
	IF IN_DDETLG <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDETLG = IN_DDETLG  --CONVERT(TIMESTAMP, '2012-02-01 12:04:00', 126) --TIMESTAMP('2012-02-01 12:04:00.000000')  --'2012-02-01 12:04:00.000000'--IN_FESTIMADA CONCAT '12:04:00.000000' --WK_HORA_MINUTO 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDETLG = NULL  --CONVERT(TIMESTAMP, '2012-02-01 12:04:00', 126) --TIMESTAMP('2012-02-01 12:04:00.000000')  --'2012-02-01 12:04:00.000000'--IN_FESTIMADA CONCAT '12:04:00.000000' --WK_HORA_MINUTO 
		WHERE PNCDTR = IN_PNCDTR ;	 
	END IF ; 
  
	IF IN_DDNAVE <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDNAVE = IN_DDNAVE 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DORDENES 
		SET DDNAVE = IN_DDNAVE 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DDOCEMB 
		SET DDNAVE = IN_DDNAVE 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDNAVE = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DORDENES 
		SET DDNAVE = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DDOCEMB 
		SET DDNAVE = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
	END IF ; 
  
	IF IN_DDTDES <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDTDES = IN_DDTREC 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DORDENES 
		SET DDTDES = IN_DDTDES 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = IN_DDTDES 
		WHERE PNCDTR = IN_PNCDTR AND 
		PNCDAC = 'I03' ;	 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDTDES = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . DORDENES 
		SET DDTDES = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
		 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND 
		PNCDAC = 'I03' ; 
	END IF ; 
 
  
	IF IN_DDOBVL <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDOBVL = IN_DDOBVL 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDOBVL = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
	END IF ; 
	 
	IF IN_DDAFPR <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDAFPR = IN_DDAFPR 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDAFPR = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
	END IF ; 
		 
	IF IN_VDDFINA <> '' THEN 
		UPDATE LIBORDAG . RACBASOS 
		SET DDFINA = IN_VDDFINA 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I03' ; 
	ELSE 
		UPDATE LIBORDAG . RACBASOS 
		SET DDFINA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I03' ; 
	END IF ; 
	 
	IF IN_DDNUME <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDNUME = IN_DDNUME 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDNUME = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
	END IF ; 
	 
	IF IN_DDPGDR <> '' THEN 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDPGDR = IN_DDPGDR 
		WHERE PNCDTR = IN_PNCDTR ; 
	ELSE 
		UPDATE LIBORDAG . DSEGIMP 
		SET DDPGDR = NULL 
		WHERE PNCDTR = IN_PNCDTR ; 
	END IF ; 
	 
	IF IN_DDAFOR <> '' THEN 
		UPDATE LIBORDAG . RACBASOS 
		SET DDFINA = IN_DDAFOR 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I13' ; 
	ELSE 
		UPDATE LIBORDAG . RACBASOS 
		SET DDFINA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I13' ; 
	END IF ; 
	 
	IF IN_DDPRES <> '' THEN 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = IN_DDPRES 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I16' ; 
	ELSE 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I16' ;	 
	END IF ; 
  
	IF IN_DDLEVA <> '' THEN 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = IN_DDLEVA 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I12' ; 
	ELSE 
		UPDATE LIBORDAG . RACBASOS 
		SET DDINIA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I12' ;		 
	END IF ; 
  
	IF IN_DDRETI <> '' THEN 
		UPDATE LIBORDAG . RACBASOS 
		SET DDFINA = IN_DDRETI 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I15' ; 
	ELSE 
		UPDATE LIBORDAG . RACBASOS 
		SET	DDFINA = NULL 
		WHERE PNCDTR = IN_PNCDTR AND PNCDAC = 'I15' ; 
	END IF ; 
	 
	UPDATE LIBORDAG . DSEGIMP SET 
	DDRDDC = IN_RECEPCION , 
	DDCRDP = IN_CARGA , 
	DDOEMB = IN_EMBARQUE , 
	DNSBRE = IN_SOBREESTADIA , 
	DNDSLB = IN_DLIBRES		 
	WHERE PNCDTR = IN_PNCDTR ; 
				 
	END  
	
	GO
	
	GRANT ALL PRIVILEGES ON PROCEDURE DC@RNSLIB.SP_SOLSEGORD_IMP_INSERTAR_FECHA_CHECKPOINT TO PUBLIC
 