CREATE PROCEDURE LIBORDAG.SP_WEBAGENCIAS_GETTABLE ( 
	IN IN_TABLA VARCHAR(2) , 
	IN IN_PARAM1 VARCHAR(8) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC LIBORDAG.SP_WEBAGENCIAS_GETTABLE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = QGPL , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
DECLARE STRSQL VARCHAR ( 6000 ) DEFAULT '' ; 
DECLARE WK_LIBRERIA VARCHAR ( 10 ) ; 
DECLARE P1 CURSOR WITH RETURN FOR S1 ; 
  
--Declarando Variables Para  capturar el valor 
--SET STRSQL = 'SELECT * FROM ' || IN_LIBRERIA || '.ZZWD08 WHERE 1 ' ; 
CASE IN_TABLA 
WHEN 'TO' THEN 
SET STRSQL = 'SELECT  a.PNCDOP, b.DCDSOP, a.PNCDRG FROM   LIBORDAG.ROPEREG a, LIBORDAG.COPERACI  b
WHERE   a.PNCDOP = b.PNCDOP AND a.PNCDRG = ''' || IN_PARAM1 || '''  ORDER BY b.DCDSOP' ; 
WHEN 'RE' THEN 
SET STRSQL = 'SELECT PNCDRG, DCDSRG FROM LIBORDAG.CREGIMEN ORDER BY DCDSRG' ; 
WHEN 'TP' THEN 
SET STRSQL = 'SELECT PNCDIN, DCDSCD FROM LIBORDAG.VTIPPAGAD ' ; 
WHEN 'AD' THEN 
SET STRSQL = 'SELECT PNCDIN, DCDSCD FROM LIBORDAG.VADUANA ORDER BY DCDSCD' ; 
WHEN 'PR' THEN 
SET STRSQL = 'SELECT PNCDIN, DCDSCD FROM LIBORDAG.VPRIODESP' ; 
WHEN 'ME' THEN 
SET STRSQL = 'SELECT PNCDIN, DCDSCD FROM LIBORDAG.VVIATRANS' ; 
WHEN 'CL' THEN 
SET STRSQL = 'SELECT DCASCI1, DCNMCL FROM LIBORDAG.DCLIENTE ORDER BY DCNMCL' ; 
WHEN 'ZO' THEN 
SET STRSQL = 'SELECT CZNFCC, TZNFCC FROM DC@RNSLIB.RZIK14' ; 
WHEN 'TC' THEN 
SET STRSQL = 'SELECT PNCDIN, DCDSCD FROM LIBORDAG.PCODIGOS WHERE PCTABL = ''TIPCARGA'' ' ; 
WHEN 'PA' THEN 
SET STRSQL = 'SELECT   DCAUX1 FROM LIBORDAG.PCODIGOS WHERE PCTABL = ''PRIODESP'' AND PNCDIN = ''' || IN_PARAM1 || '''   ' ; 
END CASE ; 
  
PREPARE S1 FROM STRSQL ; 
OPEN P1 ; 
  
END  ;
 