'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5466.
'
Namespace EnviaInformacion_Prod
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Servicios_WHSESoap", [Namespace]:="ServiciosMIQ")>  _
    Partial Public Class Servicios_WHSE
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Get_PO_StringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_PO_Detalle_StringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_Embarque_StringOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_POOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_PO_DetalleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_EmbarqueOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_PO_DetalleByPLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Get_FileNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_BLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_CheckPoint_BLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_CostsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_CheckPoint_PLBoxOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_LoadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Put_AsocLoad_PLBoxOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Emp_Datos.My.MySettings.Default.Emp_Datos_EnviaInformacion_Prod_Servicios_WHSE
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Get_PO_StringCompleted As Get_PO_StringCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_PO_Detalle_StringCompleted As Get_PO_Detalle_StringCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_Embarque_StringCompleted As Get_Embarque_StringCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_POCompleted As Get_POCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_PO_DetalleCompleted As Get_PO_DetalleCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_EmbarqueCompleted As Get_EmbarqueCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_PO_DetalleByPLCompleted As Get_PO_DetalleByPLCompletedEventHandler
        
        '''<remarks/>
        Public Event Get_FileNumberCompleted As Get_FileNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_BLCompleted As Put_BLCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_CheckPoint_BLCompleted As Put_CheckPoint_BLCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_CostsCompleted As Put_CostsCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_CheckPoint_PLBoxCompleted As Put_CheckPoint_PLBoxCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_LoadCompleted As Put_LoadCompletedEventHandler
        
        '''<remarks/>
        Public Event Put_AsocLoad_PLBoxCompleted As Put_AsocLoad_PLBoxCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_PO_String", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_PO_String(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String) As String
            Dim results() As Object = Me.Invoke("Get_PO_String", New Object() {COD_GUID, CIDCUS, FechaIni, FechaFin})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_PO_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String)
            Me.Get_PO_StringAsync(COD_GUID, CIDCUS, FechaIni, FechaFin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_PO_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String, ByVal userState As Object)
            If (Me.Get_PO_StringOperationCompleted Is Nothing) Then
                Me.Get_PO_StringOperationCompleted = AddressOf Me.OnGet_PO_StringOperationCompleted
            End If
            Me.InvokeAsync("Get_PO_String", New Object() {COD_GUID, CIDCUS, FechaIni, FechaFin}, Me.Get_PO_StringOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_PO_StringOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_PO_StringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_PO_StringCompleted(Me, New Get_PO_StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_PO_Detalle_String", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_PO_Detalle_String(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String) As String
            Dim results() As Object = Me.Invoke("Get_PO_Detalle_String", New Object() {COD_GUID, CIDCUS, CIDPO})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_PO_Detalle_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String)
            Me.Get_PO_Detalle_StringAsync(COD_GUID, CIDCUS, CIDPO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_PO_Detalle_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String, ByVal userState As Object)
            If (Me.Get_PO_Detalle_StringOperationCompleted Is Nothing) Then
                Me.Get_PO_Detalle_StringOperationCompleted = AddressOf Me.OnGet_PO_Detalle_StringOperationCompleted
            End If
            Me.InvokeAsync("Get_PO_Detalle_String", New Object() {COD_GUID, CIDCUS, CIDPO}, Me.Get_PO_Detalle_StringOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_PO_Detalle_StringOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_PO_Detalle_StringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_PO_Detalle_StringCompleted(Me, New Get_PO_Detalle_StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_Embarque_String", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Embarque_String(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String) As String
            Dim results() As Object = Me.Invoke("Get_Embarque_String", New Object() {COD_GUID, CIDCUS, FILENUM})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_Embarque_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String)
            Me.Get_Embarque_StringAsync(COD_GUID, CIDCUS, FILENUM, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_Embarque_StringAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal userState As Object)
            If (Me.Get_Embarque_StringOperationCompleted Is Nothing) Then
                Me.Get_Embarque_StringOperationCompleted = AddressOf Me.OnGet_Embarque_StringOperationCompleted
            End If
            Me.InvokeAsync("Get_Embarque_String", New Object() {COD_GUID, CIDCUS, FILENUM}, Me.Get_Embarque_StringOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_Embarque_StringOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_Embarque_StringCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_Embarque_StringCompleted(Me, New Get_Embarque_StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_PO", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_PO(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_PO", New Object() {COD_GUID, CIDCUS, FechaIni, FechaFin})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_POAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String)
            Me.Get_POAsync(COD_GUID, CIDCUS, FechaIni, FechaFin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_POAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FechaIni As String, ByVal FechaFin As String, ByVal userState As Object)
            If (Me.Get_POOperationCompleted Is Nothing) Then
                Me.Get_POOperationCompleted = AddressOf Me.OnGet_POOperationCompleted
            End If
            Me.InvokeAsync("Get_PO", New Object() {COD_GUID, CIDCUS, FechaIni, FechaFin}, Me.Get_POOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_POOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_POCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_POCompleted(Me, New Get_POCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_PO_Detalle", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_PO_Detalle(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_PO_Detalle", New Object() {COD_GUID, CIDCUS, CIDPO})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_PO_DetalleAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String)
            Me.Get_PO_DetalleAsync(COD_GUID, CIDCUS, CIDPO, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_PO_DetalleAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPO As String, ByVal userState As Object)
            If (Me.Get_PO_DetalleOperationCompleted Is Nothing) Then
                Me.Get_PO_DetalleOperationCompleted = AddressOf Me.OnGet_PO_DetalleOperationCompleted
            End If
            Me.InvokeAsync("Get_PO_Detalle", New Object() {COD_GUID, CIDCUS, CIDPO}, Me.Get_PO_DetalleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_PO_DetalleOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_PO_DetalleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_PO_DetalleCompleted(Me, New Get_PO_DetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_Embarque", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_Embarque(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_Embarque", New Object() {COD_GUID, CIDCUS, FILENUM})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_EmbarqueAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String)
            Me.Get_EmbarqueAsync(COD_GUID, CIDCUS, FILENUM, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_EmbarqueAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal userState As Object)
            If (Me.Get_EmbarqueOperationCompleted Is Nothing) Then
                Me.Get_EmbarqueOperationCompleted = AddressOf Me.OnGet_EmbarqueOperationCompleted
            End If
            Me.InvokeAsync("Get_Embarque", New Object() {COD_GUID, CIDCUS, FILENUM}, Me.Get_EmbarqueOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_EmbarqueOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_EmbarqueCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_EmbarqueCompleted(Me, New Get_EmbarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_PO_DetalleByPL", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_PO_DetalleByPL(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal GUIAREMISION As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("Get_PO_DetalleByPL", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, GUIAREMISION})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_PO_DetalleByPLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal GUIAREMISION As String)
            Me.Get_PO_DetalleByPLAsync(COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, GUIAREMISION, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_PO_DetalleByPLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal GUIAREMISION As String, ByVal userState As Object)
            If (Me.Get_PO_DetalleByPLOperationCompleted Is Nothing) Then
                Me.Get_PO_DetalleByPLOperationCompleted = AddressOf Me.OnGet_PO_DetalleByPLOperationCompleted
            End If
            Me.InvokeAsync("Get_PO_DetalleByPL", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, GUIAREMISION}, Me.Get_PO_DetalleByPLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_PO_DetalleByPLOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_PO_DetalleByPLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_PO_DetalleByPLCompleted(Me, New Get_PO_DetalleByPLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Get_FileNumber", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Get_FileNumber(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal ConEmbarque As String) As String
            Dim results() As Object = Me.Invoke("Get_FileNumber", New Object() {COD_GUID, CIDCUS, ConEmbarque})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Get_FileNumberAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal ConEmbarque As String)
            Me.Get_FileNumberAsync(COD_GUID, CIDCUS, ConEmbarque, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Get_FileNumberAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal ConEmbarque As String, ByVal userState As Object)
            If (Me.Get_FileNumberOperationCompleted Is Nothing) Then
                Me.Get_FileNumberOperationCompleted = AddressOf Me.OnGet_FileNumberOperationCompleted
            End If
            Me.InvokeAsync("Get_FileNumber", New Object() {COD_GUID, CIDCUS, ConEmbarque}, Me.Get_FileNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnGet_FileNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.Get_FileNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Get_FileNumberCompleted(Me, New Get_FileNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_BL", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_BL(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal NORDAGE As Integer, ByVal DORDAGE As String, ByVal STIPREG As String, ByVal SNOMTER As String, ByVal SDIALIB As Integer, ByVal SSOBEST As Integer, ByVal SCANAL As String, ByVal SOBS As String, ByVal CCODCON As String, ByVal SDUA As String) As String
            Dim results() As Object = Me.Invoke("Put_BL", New Object() {COD_GUID, CIDCUS, FILENUM, NORDAGE, DORDAGE, STIPREG, SNOMTER, SDIALIB, SSOBEST, SCANAL, SOBS, CCODCON, SDUA})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_BLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal NORDAGE As Integer, ByVal DORDAGE As String, ByVal STIPREG As String, ByVal SNOMTER As String, ByVal SDIALIB As Integer, ByVal SSOBEST As Integer, ByVal SCANAL As String, ByVal SOBS As String, ByVal CCODCON As String, ByVal SDUA As String)
            Me.Put_BLAsync(COD_GUID, CIDCUS, FILENUM, NORDAGE, DORDAGE, STIPREG, SNOMTER, SDIALIB, SSOBEST, SCANAL, SOBS, CCODCON, SDUA, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_BLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal NORDAGE As Integer, ByVal DORDAGE As String, ByVal STIPREG As String, ByVal SNOMTER As String, ByVal SDIALIB As Integer, ByVal SSOBEST As Integer, ByVal SCANAL As String, ByVal SOBS As String, ByVal CCODCON As String, ByVal SDUA As String, ByVal userState As Object)
            If (Me.Put_BLOperationCompleted Is Nothing) Then
                Me.Put_BLOperationCompleted = AddressOf Me.OnPut_BLOperationCompleted
            End If
            Me.InvokeAsync("Put_BL", New Object() {COD_GUID, CIDCUS, FILENUM, NORDAGE, DORDAGE, STIPREG, SNOMTER, SDIALIB, SSOBEST, SCANAL, SOBS, CCODCON, SDUA}, Me.Put_BLOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_BLOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_BLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_BLCompleted(Me, New Put_BLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_CheckPoint_BL", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_CheckPoint_BL(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DCRECP As String, ByVal CESTOBJ As String) As String
            Dim results() As Object = Me.Invoke("Put_CheckPoint_BL", New Object() {COD_GUID, CIDCUS, FILENUM, CCHKPNT, NOBSCP, DCRECP, CESTOBJ})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_CheckPoint_BLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DCRECP As String, ByVal CESTOBJ As String)
            Me.Put_CheckPoint_BLAsync(COD_GUID, CIDCUS, FILENUM, CCHKPNT, NOBSCP, DCRECP, CESTOBJ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_CheckPoint_BLAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal FILENUM As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DCRECP As String, ByVal CESTOBJ As String, ByVal userState As Object)
            If (Me.Put_CheckPoint_BLOperationCompleted Is Nothing) Then
                Me.Put_CheckPoint_BLOperationCompleted = AddressOf Me.OnPut_CheckPoint_BLOperationCompleted
            End If
            Me.InvokeAsync("Put_CheckPoint_BL", New Object() {COD_GUID, CIDCUS, FILENUM, CCHKPNT, NOBSCP, DCRECP, CESTOBJ}, Me.Put_CheckPoint_BLOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_CheckPoint_BLOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_CheckPoint_BLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_CheckPoint_BLCompleted(Me, New Put_CheckPoint_BLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_Costs", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_Costs(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal TIPCOST As String, ByVal CCID As Integer, ByVal CODENTIDAD As String, ByVal CTIPCOST As Integer, ByVal TCOMMENTS As String, ByVal CPAIDTYPE As String, ByVal SVALBUY As Decimal, ByVal SVALSEL As Decimal, ByVal SVALEXCHANGERATE As Decimal, ByVal CESTOBJ As String) As String
            Dim results() As Object = Me.Invoke("Put_Costs", New Object() {COD_GUID, CIDCUS, TIPCOST, CCID, CODENTIDAD, CTIPCOST, TCOMMENTS, CPAIDTYPE, SVALBUY, SVALSEL, SVALEXCHANGERATE, CESTOBJ})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_CostsAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal TIPCOST As String, ByVal CCID As Integer, ByVal CODENTIDAD As String, ByVal CTIPCOST As Integer, ByVal TCOMMENTS As String, ByVal CPAIDTYPE As String, ByVal SVALBUY As Decimal, ByVal SVALSEL As Decimal, ByVal SVALEXCHANGERATE As Decimal, ByVal CESTOBJ As String)
            Me.Put_CostsAsync(COD_GUID, CIDCUS, TIPCOST, CCID, CODENTIDAD, CTIPCOST, TCOMMENTS, CPAIDTYPE, SVALBUY, SVALSEL, SVALEXCHANGERATE, CESTOBJ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_CostsAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal TIPCOST As String, ByVal CCID As Integer, ByVal CODENTIDAD As String, ByVal CTIPCOST As Integer, ByVal TCOMMENTS As String, ByVal CPAIDTYPE As String, ByVal SVALBUY As Decimal, ByVal SVALSEL As Decimal, ByVal SVALEXCHANGERATE As Decimal, ByVal CESTOBJ As String, ByVal userState As Object)
            If (Me.Put_CostsOperationCompleted Is Nothing) Then
                Me.Put_CostsOperationCompleted = AddressOf Me.OnPut_CostsOperationCompleted
            End If
            Me.InvokeAsync("Put_Costs", New Object() {COD_GUID, CIDCUS, TIPCOST, CCID, CODENTIDAD, CTIPCOST, TCOMMENTS, CPAIDTYPE, SVALBUY, SVALSEL, SVALEXCHANGERATE, CESTOBJ}, Me.Put_CostsOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_CostsOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_CostsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_CostsCompleted(Me, New Put_CostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_CheckPoint_PLBox", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_CheckPoint_PLBox(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DFECCRE As String, ByVal CESTOBJ As String) As String
            Dim results() As Object = Me.Invoke("Put_CheckPoint_PLBox", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, NOBSCP, DFECCRE, CESTOBJ})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_CheckPoint_PLBoxAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DFECCRE As String, ByVal CESTOBJ As String)
            Me.Put_CheckPoint_PLBoxAsync(COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, NOBSCP, DFECCRE, CESTOBJ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_CheckPoint_PLBoxAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal CCHKPNT As Integer, ByVal NOBSCP As String, ByVal DFECCRE As String, ByVal CESTOBJ As String, ByVal userState As Object)
            If (Me.Put_CheckPoint_PLBoxOperationCompleted Is Nothing) Then
                Me.Put_CheckPoint_PLBoxOperationCompleted = AddressOf Me.OnPut_CheckPoint_PLBoxOperationCompleted
            End If
            Me.InvokeAsync("Put_CheckPoint_PLBox", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, CCHKPNT, NOBSCP, DFECCRE, CESTOBJ}, Me.Put_CheckPoint_PLBoxOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_CheckPoint_PLBoxOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_CheckPoint_PLBoxCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_CheckPoint_PLBoxCompleted(Me, New Put_CheckPoint_PLBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_Load", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_Load( _
                    ByVal COD_GUID As String,  _
                    ByVal CIDCUS As Integer,  _
                    ByVal CCLIENT As Integer,  _
                    ByVal NNROLOAD As String,  _
                    ByVal CTRANSP As Integer,  _
                    ByVal NCARGUILOA As String,  _
                    ByVal NVEHDESLOA As String,  _
                    ByVal CTYPLA As Integer,  _
                    ByVal NDRV As String,  _
                    ByVal NDLVTCK As String,  _
                    ByVal NATTPLALOA As String,  _
                    ByVal NTRAPLALOA As String,  _
                    ByVal SWEILOA As Decimal,  _
                    ByVal CUNIMEDWEI As Integer,  _
                    ByVal STOTBULK As Decimal,  _
                    ByVal NCTCLOA As String,  _
                    ByVal CESTOBJ As String) As String
            Dim results() As Object = Me.Invoke("Put_Load", New Object() {COD_GUID, CIDCUS, CCLIENT, NNROLOAD, CTRANSP, NCARGUILOA, NVEHDESLOA, CTYPLA, NDRV, NDLVTCK, NATTPLALOA, NTRAPLALOA, SWEILOA, CUNIMEDWEI, STOTBULK, NCTCLOA, CESTOBJ})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_LoadAsync( _
                    ByVal COD_GUID As String,  _
                    ByVal CIDCUS As Integer,  _
                    ByVal CCLIENT As Integer,  _
                    ByVal NNROLOAD As String,  _
                    ByVal CTRANSP As Integer,  _
                    ByVal NCARGUILOA As String,  _
                    ByVal NVEHDESLOA As String,  _
                    ByVal CTYPLA As Integer,  _
                    ByVal NDRV As String,  _
                    ByVal NDLVTCK As String,  _
                    ByVal NATTPLALOA As String,  _
                    ByVal NTRAPLALOA As String,  _
                    ByVal SWEILOA As Decimal,  _
                    ByVal CUNIMEDWEI As Integer,  _
                    ByVal STOTBULK As Decimal,  _
                    ByVal NCTCLOA As String,  _
                    ByVal CESTOBJ As String)
            Me.Put_LoadAsync(COD_GUID, CIDCUS, CCLIENT, NNROLOAD, CTRANSP, NCARGUILOA, NVEHDESLOA, CTYPLA, NDRV, NDLVTCK, NATTPLALOA, NTRAPLALOA, SWEILOA, CUNIMEDWEI, STOTBULK, NCTCLOA, CESTOBJ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_LoadAsync( _
                    ByVal COD_GUID As String,  _
                    ByVal CIDCUS As Integer,  _
                    ByVal CCLIENT As Integer,  _
                    ByVal NNROLOAD As String,  _
                    ByVal CTRANSP As Integer,  _
                    ByVal NCARGUILOA As String,  _
                    ByVal NVEHDESLOA As String,  _
                    ByVal CTYPLA As Integer,  _
                    ByVal NDRV As String,  _
                    ByVal NDLVTCK As String,  _
                    ByVal NATTPLALOA As String,  _
                    ByVal NTRAPLALOA As String,  _
                    ByVal SWEILOA As Decimal,  _
                    ByVal CUNIMEDWEI As Integer,  _
                    ByVal STOTBULK As Decimal,  _
                    ByVal NCTCLOA As String,  _
                    ByVal CESTOBJ As String,  _
                    ByVal userState As Object)
            If (Me.Put_LoadOperationCompleted Is Nothing) Then
                Me.Put_LoadOperationCompleted = AddressOf Me.OnPut_LoadOperationCompleted
            End If
            Me.InvokeAsync("Put_Load", New Object() {COD_GUID, CIDCUS, CCLIENT, NNROLOAD, CTRANSP, NCARGUILOA, NVEHDESLOA, CTYPLA, NDRV, NDLVTCK, NATTPLALOA, NTRAPLALOA, SWEILOA, CUNIMEDWEI, STOTBULK, NCTCLOA, CESTOBJ}, Me.Put_LoadOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_LoadOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_LoadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_LoadCompleted(Me, New Put_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ServiciosMIQ/Put_AsocLoad_PLBox", RequestNamespace:="ServiciosMIQ", ResponseNamespace:="ServiciosMIQ", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Put_AsocLoad_PLBox(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal NNROLOAD As String, ByVal CESTOBJ As String) As String
            Dim results() As Object = Me.Invoke("Put_AsocLoad_PLBox", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, NNROLOAD, CESTOBJ})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Put_AsocLoad_PLBoxAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal NNROLOAD As String, ByVal CESTOBJ As String)
            Me.Put_AsocLoad_PLBoxAsync(COD_GUID, CIDCUS, CIDPL, CBOXNO, NNROLOAD, CESTOBJ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Put_AsocLoad_PLBoxAsync(ByVal COD_GUID As String, ByVal CIDCUS As Integer, ByVal CIDPL As String, ByVal CBOXNO As String, ByVal NNROLOAD As String, ByVal CESTOBJ As String, ByVal userState As Object)
            If (Me.Put_AsocLoad_PLBoxOperationCompleted Is Nothing) Then
                Me.Put_AsocLoad_PLBoxOperationCompleted = AddressOf Me.OnPut_AsocLoad_PLBoxOperationCompleted
            End If
            Me.InvokeAsync("Put_AsocLoad_PLBox", New Object() {COD_GUID, CIDCUS, CIDPL, CBOXNO, NNROLOAD, CESTOBJ}, Me.Put_AsocLoad_PLBoxOperationCompleted, userState)
        End Sub
        
        Private Sub OnPut_AsocLoad_PLBoxOperationCompleted(ByVal arg As Object)
            If (Not (Me.Put_AsocLoad_PLBoxCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Put_AsocLoad_PLBoxCompleted(Me, New Put_AsocLoad_PLBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_PO_StringCompletedEventHandler(ByVal sender As Object, ByVal e As Get_PO_StringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_PO_StringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_PO_Detalle_StringCompletedEventHandler(ByVal sender As Object, ByVal e As Get_PO_Detalle_StringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_PO_Detalle_StringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_Embarque_StringCompletedEventHandler(ByVal sender As Object, ByVal e As Get_Embarque_StringCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_Embarque_StringCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_POCompletedEventHandler(ByVal sender As Object, ByVal e As Get_POCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_POCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_PO_DetalleCompletedEventHandler(ByVal sender As Object, ByVal e As Get_PO_DetalleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_PO_DetalleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_EmbarqueCompletedEventHandler(ByVal sender As Object, ByVal e As Get_EmbarqueCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_EmbarqueCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_PO_DetalleByPLCompletedEventHandler(ByVal sender As Object, ByVal e As Get_PO_DetalleByPLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_PO_DetalleByPLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Get_FileNumberCompletedEventHandler(ByVal sender As Object, ByVal e As Get_FileNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Get_FileNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_BLCompletedEventHandler(ByVal sender As Object, ByVal e As Put_BLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_BLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_CheckPoint_BLCompletedEventHandler(ByVal sender As Object, ByVal e As Put_CheckPoint_BLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_CheckPoint_BLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_CostsCompletedEventHandler(ByVal sender As Object, ByVal e As Put_CostsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_CostsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_CheckPoint_PLBoxCompletedEventHandler(ByVal sender As Object, ByVal e As Put_CheckPoint_PLBoxCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_CheckPoint_PLBoxCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_LoadCompletedEventHandler(ByVal sender As Object, ByVal e As Put_LoadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_LoadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub Put_AsocLoad_PLBoxCompletedEventHandler(ByVal sender As Object, ByVal e As Put_AsocLoad_PLBoxCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Put_AsocLoad_PLBoxCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
